apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lVQWxFemdrQ0pSd0VscWxNL2ZzMjl5TnBlVnVBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01NVEF1TVRVeUxqRTRNeTR4TUI0WERUSXpNRFl4TlRBNE1UVXdPVm9YRFRNegpNRFl4TWpBNE1UVXdPVm93RnpFVk1CTUdBMVVFQXd3TU1UQXVNVFV5TGpFNE15NHhNSUlCSWpBTkJna3Foa2lHCjl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF4Und3YmJINWhBQm11TnlRVHFlcFh6bVJ2T3RkTTlhSnBXMm0KVytSNGNBcFpYOHNNQ0Nkb2dzbnhqc2pSY3VsU0FwOU9zYURYSUlMY0N0VUpiWjdmOUlaVUlBYW5TUEdyQUdCTQpmalA1bTlneDJkWkdGcHBqWU50cjVtbnpmSjhmL0pLL29PUHlHV1hDMHNSeWRMRGxYYmR5Q2xjT2lpakRlU0ZXCi9lVnVNR2U4K2k1OXd4Zk1VWlN2Z3FIMUxaVGpoRlFoWDY3SVR3SEQ4LzRGaXMzMDgvdkJhRkZSK1JtNmRrT3oKaEwzWFBBS0xoOGNXU1p6NVM4YktlMDErYk53SFBpMWtjdG9PQVhSYXZVMHJpVEo2ZDRiaVVSQ1N5RzVQa0ZoKwplcis0dG5RSVdNVjRwWVNFd3Y5NXhkQ3hNWkE4QmJQVzBuY1dkbGdFdE5lam9VREhNUUlEQVFBQm8xTXdVVEFkCkJnTlZIUTRFRmdRVUI0V2haVS9sYUx5UzhPNVZBeDVUSk1NRDVoRXdId1lEVlIwakJCZ3dGb0FVQjRXaFpVL2wKYUx5UzhPNVZBeDVUSk1NRDVoRXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBQmlHaVhoUm5Kb2ZpUWRwcTlYeTlWckdWckNsRC9oMmRudEdkYVpiN1ozdHpIWWdraFRJUi93OXB1cUk4CmIxSUdaZ2NnRWttOENwYjdBZjRTOEZrek50SXc1RGx6d0dkUSt6WGRTRDdWMU5leFN4V2t1OWIyMG01am50VjgKM3JDMWZzdUdGRWpLYUVZSVZNTks2R2dFM0l1dGorTmlSOG5WdE5Ca0t6ZHZDRXJoRFMwckYycGtMSHIyKzg4Vwp4dGJUWURrOUkvczd2cWhGKzAvUmZFU2djSUZ1OVh5aXpJaFBpYVFMRFdHT1Z3VmhKRGJDMUNNcEhoZlQxYVdqCndpblZ2ODRVODlKejIwNDVCUERGUHBiZ1BmOWhyak1WY0d2eXBlSjA1L2xEaEhWTWpiUWczVmd0YjNaZmZDdTMKT2JHU3R5Q1FOUzdLK3FrUEtwd25QRmxna2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://10.1.1.6:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    namespace: arcadiacrypto
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: WFdndnpOYjFnR1BnaDVWMFVQcTNrWkhVNmxoWTVGTlBJRnFCU2FIOGx4ND0K
